# frozen_string_literal: true

require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "lib" << "test"
  t.test_files = FileList["test/test_*.rb"]
  t.warning = true
end

desc "Run the shared conformance suite"
task :conformance do
  ruby "-Ilib", "exe/spdf", "conformance", File.expand_path("../conformance", __dir__)
end

task default: :test
