//! Raw FFI bindings to llama.cpp and its multimodal library (mtmd), generated by bindgen at
//! build time. Use the safe API of the `spdf-infer` crate instead.
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code, clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/// The llama.cpp commit these bindings were built from.
pub const LLAMA_COMMIT: &str = env!("SPDF_LLAMA_COMMIT");
