/** Paths, the Node engine host and the Fluent strings shared by the tests. */

import { mkdtempSync, readFileSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import { open, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { EngineHost } from '../../src/engine.js';
import { fakeSqlite, type FakeSqlite } from './fake-mozstorage.js';

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
export const FIXTURES = join(ROOT, '..', 'fixtures');
export const EN = join(FIXTURES, 'spdf-in-five-pages.spdf');
export const ES = join(FIXTURES, 'spdf-en-cinco-paginas.spdf');
export const ROTO = join(FIXTURES, 'roto.spdf');
export const LEGACY_41 = join(ROOT, '..', '..', 'conformance', 'legacy', 'garcilaso-4.1.spdf');
export const LEGACY_40 = join(ROOT, '..', '..', 'conformance', 'legacy', 'kennedy-4.0.spdf');

/**
 * `documents.source_sha256` of a fixture, read with plain SQL. The fixtures are
 * regenerated by the website's build (`site/muestras`), so the hashes are not
 * hard-coded here.
 */
export function sourceSha256(path: string): string {
  const db = new DatabaseSync(path, { readOnly: true });
  try {
    const row = db.prepare('SELECT source_sha256 AS h FROM documents').get() as { h: string };
    return row.h;
  } finally {
    db.close();
  }
}

export const EN_SHA = sourceSha256(EN);
export const ES_SHA = sourceSha256(ES);

export function tempDir(prefix = 'spdf-zotero-test-'): string {
  return mkdtempSync(join(tmpdir(), prefix));
}

/** The engine host of the tests: node:fs, a temp dir, and the fake Sqlite.sys.mjs. */
export function nodeHost(dir: string, sqlite: FakeSqlite = fakeSqlite()): EngineHost & { fake: FakeSqlite } {
  let n = 0;
  return {
    fake: sqlite,
    sqlite: () => sqlite,
    readFile: (p) => readFile(p),
    async readFileHead(p, length) {
      const fh = await open(p, 'r');
      try {
        const buf = Buffer.alloc(length);
        const { bytesRead } = await fh.read(buf, 0, length, 0);
        return buf.subarray(0, bytesRead);
      } finally {
        await fh.close();
      }
    },
    writeFile: (p, d) => writeFile(p, d),
    remove: (p) => rm(p, { force: true }),
    tempPath: (prefix) => join(dir, `${prefix}${n++}.sqlite`),
    decompressionStream: () => globalThis.DecompressionStream as never,
  };
}

// ---------------------------------------------------------------------------
// Fluent
// ---------------------------------------------------------------------------

export interface FtlMessage {
  value: string | null;
  attributes: Record<string, string>;
}

/** A small parser for the subset of Fluent the plugin uses (single-line values and attributes). */
export function parseFtl(text: string): Map<string, FtlMessage> {
  const out = new Map<string, FtlMessage>();
  let current: FtlMessage | null = null;
  for (const line of text.split('\n')) {
    if (!line.trim() || line.startsWith('#')) {
      if (!line.trim()) current = null;
      continue;
    }
    const msg = /^([a-z][a-z0-9-]*)\s*=\s*(.*)$/.exec(line);
    if (msg) {
      current = { value: (msg[2] as string).trim() || null, attributes: {} };
      if (out.has(msg[1] as string)) throw new Error(`duplicate id ${msg[1]}`);
      out.set(msg[1] as string, current);
      continue;
    }
    const attr = /^\s+\.([a-z][a-z0-9-]*)\s*=\s*(.*)$/.exec(line);
    if (attr && current) {
      current.attributes[attr[1] as string] = (attr[2] as string).trim();
      continue;
    }
    throw new Error(`unparsed FTL line: ${line}`);
  }
  return out;
}

export function ftl(locale: 'en-US' | 'es-ES'): Map<string, FtlMessage> {
  return parseFtl(readFileSync(join(ROOT, 'addon', 'locale', locale, 'spdf-zotero.ftl'), 'utf8'));
}

/** A `Translate` over an FTL file; unknown ids throw, so a missing string fails the test. */
export function translator(locale: 'en-US' | 'es-ES' = 'en-US') {
  const messages = ftl(locale);
  return async (id: string, args: Record<string, string | number> = {}): Promise<string> => {
    const m = messages.get(id);
    if (!m || m.value === null) throw new Error(`missing Fluent string ${id}`);
    return m.value.replace(/\{\s*\$([a-z]+)\s*\}/g, (_, k: string) => {
      if (!(k in args)) throw new Error(`missing argument ${k} for ${id}`);
      return String(args[k]);
    });
  };
}
