/*
 * spdf.h: C ABI of the SPDF reference implementation (Rust).
 *
 * Conventions: every function returns an int status (SPDF_OK = 0) and writes its
 * result through an out parameter. Strings are UTF-8 and NUL-terminated; strings
 * returned by the library are owned by the caller and released with
 * spdf_string_free(); byte buffers with spdf_bytes_free(). Complex values are JSON.
 * After a failure, spdf_last_error() returns {"status","code","message"} for the
 * calling thread. A SpdfDoc handle may be used from one thread at a time.
 *
 * SPDX-License-Identifier: MIT OR Apache-2.0
 */

#ifndef SPDF_H
#define SPDF_H

/* Generated by cbindgen from rust/crates/spdf-ffi. Do not edit by hand: run `cbindgen --config cbindgen.toml --output include/spdf.h` in rust/crates/spdf-ffi. */

#include <stddef.h>
#include <stdint.h>

/*
 Success.
 */
#define SPDF_OK 0

/*
 A required argument is NULL or not valid UTF-8/JSON.
 */
#define SPDF_ERR_ARGUMENT 1

/*
 File or I/O error.
 */
#define SPDF_ERR_IO 2

/*
 The data is not a valid or supported SPDF (see the error code).
 */
#define SPDF_ERR_FORMAT 3

/*
 Something requested does not exist.
 */
#define SPDF_ERR_NOT_FOUND 4

/*
 Any other error (SQLite, internal).
 */
#define SPDF_ERR_OTHER 5

/*
 A Rust panic was caught at the boundary.
 */
#define SPDF_ERR_PANIC 6

/*
 An open SPDF document (opaque).
 */
typedef struct SpdfDoc SpdfDoc;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/*
 Library version (static string, do not free).
 */
const char *spdf_version(void);

/*
 Last error of the calling thread as JSON `{"status","code","message"}`,
 or an empty string. Valid until the next library call on this thread.
 */
const char *spdf_last_error(void);

/*
 Frees a string returned by the library. NULL is ignored.
 */
void spdf_string_free(char *s);

/*
 Frees a byte buffer returned by the library. NULL is ignored.
 */
void spdf_bytes_free(uint8_t *data, size_t len);

/*
 Opens a file safely. `options_json` may be NULL or
 `{"max_blob_bytes","max_decompressed_bytes","known_extensions","ignore_required_extensions"}`.
 */
int spdf_open(const char *path, const char *options_json, struct SpdfDoc **out);

/*
 Opens an SPDF held in memory (SQLite or gzip-wrapped SQLite).
 */
int spdf_open_bytes(const uint8_t *data,
                    size_t len,
                    const char *options_json,
                    struct SpdfDoc **out);

/*
 Closes a document. NULL is ignored.
 */
void spdf_close(struct SpdfDoc *doc);

/*
 Format version of an open document (`"5.0"`, `"4.1"`…); free with `spdf_string_free`.
 */
int spdf_doc_version(const struct SpdfDoc *doc, char **out);

/*
 Validates a file; writes the §12 report as JSON. Returns `SPDF_OK` even
 when the file is invalid (read `"valid"`).
 */
int spdf_validate(const char *path, char **out_json);

/*
 Validates an in-memory file.
 */
int spdf_validate_bytes(const uint8_t *data, size_t len, char **out_json);

/*
 Canonical dump (§5) serialized with RFC 8785 (JCS).
 */
int spdf_dump(const struct SpdfDoc *doc, char **out_json);

/*
 `spdf_meta` as a JSON object.
 */
int spdf_meta(const struct SpdfDoc *doc, char **out_json);

/*
 The document row as JSON (metadata is the CSL-JSON item).
 */
int spdf_document(const struct SpdfDoc *doc, char **out_json);

/*
 Units as a JSON array (reading order).
 */
int spdf_units(const struct SpdfDoc *doc, char **out_json);

/*
 Fragments as a JSON array (by `n`).
 */
int spdf_fragments(const struct SpdfDoc *doc, char **out_json);

/*
 Sections, figures and spaces as one JSON object `{"sections","figures","spaces"}`.
 */
int spdf_structure(const struct SpdfDoc *doc, char **out_json);

/*
 Reads a blob (`key` or `blob:<key>`). Writes the bytes (free with
 `spdf_bytes_free(data, len)`) and the media type (free with
 `spdf_string_free`). Returns `SPDF_ERR_NOT_FOUND` if absent.
 */
int spdf_blob(const struct SpdfDoc *doc,
              const char *key,
              uint8_t **out_data,
              size_t *out_len,
              char **out_mime);

/*
 Lexical search (reference algorithm). Results: JSON array of
 `{fragment_id, score, via, anchor, anchor_uri}`.
 */
int spdf_search_lexical(const struct SpdfDoc *doc,
                        const char *query,
                        uint32_t limit,
                        char **out_json);

/*
 Vector search. `target` is `fragment` (default when NULL), `unit` or `figure`.
 */
int spdf_search_vector(const struct SpdfDoc *doc,
                       const char *space,
                       const char *target,
                       const float *vec,
                       size_t dims,
                       uint32_t limit,
                       char **out_json);

/*
 Hybrid search (RRF, k = 10).
 */
int spdf_search_hybrid(const struct SpdfDoc *doc,
                       const char *query,
                       const char *space,
                       const float *vec,
                       size_t dims,
                       uint32_t limit,
                       char **out_json);

/*
 Formats an anchor URI. `anchor_end_json` may be NULL.
 */
int spdf_anchor_uri_format(const char *docref,
                           const char *anchor_json,
                           const char *anchor_end_json,
                           char **out);

/*
 Formats an anchor URI from a locator (`{"p":29,"f":"21",…}`).
 */
int spdf_anchor_uri_format_locator(const char *docref, const char *locator_json, char **out);

/*
 Parses an anchor URI into `{"docref","locator"}`.
 */
int spdf_anchor_uri_parse(const char *uri, char **out_json);

/*
 Short citation from CSL metadata. `anchor_end_json` may be NULL;
 `locale` is a BCP 47 tag (`es`, `en`…; NULL = `en`).
 */
int spdf_cite(const char *metadata_json,
              const char *anchor_json,
              const char *anchor_end_json,
              const char *locale,
              char **out);

/*
 Short citation of an anchor in an open document.
 */
int spdf_doc_cite(const struct SpdfDoc *doc,
                  const char *anchor_json,
                  const char *anchor_end_json,
                  const char *locale,
                  char **out);

/*
 CSL-JSON (array with one item) of the document.
 */
int spdf_export_csl_json(const struct SpdfDoc *doc, char **out);

/*
 BibTeX entry of the document.
 */
int spdf_export_bibtex(const struct SpdfDoc *doc, char **out);

/*
 Builds a 5.0 file at `path` from a canonical dump or a conformance source
 (dump + `vectors.<space>.items` + `blobs[].data_base64`).
 */
int spdf_write_from_dump(const char *dump_json, const char *path);

/*
 Converts a legacy 4.x file to 5.0.
 */
int spdf_convert_legacy(const char *src, const char *dst);

/*
 Recomputes `content_sha256` and checks the signature; writes
 `{"computed_sha256","stored_sha256","hash_ok","signer","signature_ok","signer_trusted"}`.
 `expected_signer` (`ed25519:<base64>`) may be NULL.
 */
int spdf_verify(const struct SpdfDoc *doc, const char *expected_signer, char **out_json);

/*
 Runs the conformance suite in `dir` and writes the protocol report.
 */
int spdf_conformance_run(const char *dir, char **out_json);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SPDF_H */
