/**
 * Builds the plugin: `dist/addon/` (the unpacked plugin, handy for development with a
 * proxy file in the Zotero profile) and `dist/spdf-zotero-<version>.xpi`.
 *
 * `bootstrap.js` is the whole plugin in one file: the TypeScript sources and the
 * engine-less core of `spdf-format` bundled by esbuild into an IIFE, followed by the
 * bootstrap hooks Zotero calls. One file means the plugin never has to load a second
 * script from its own jar: (newer Firefox versions refuse `loadSubScript` on jar:
 * URLs unless told otherwise, and only Zotero's own loader does that for bootstrap.js).
 * The output is pure ASCII, so its encoding never depends on the script loader.
 */

import { build } from 'esbuild';
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { zip } from './zip.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'));
const version = pkg.version;
const dist = join(root, 'dist');
const out = join(dist, 'addon');

const HOOKS = `
// ---------------------------------------------------------------------------
// Bootstrap hooks. Zotero loads this file into the plugin's sandbox and calls these
// functions by name. The globals of that sandbox are handed to the plugin explicitly.
// ---------------------------------------------------------------------------
var spdfZoteroPlugin;

function spdfZoteroGlobals() {
  return {
    Zotero: Zotero,
    Services: Services,
    ChromeUtils: ChromeUtils,
    IOUtils: IOUtils,
    PathUtils: PathUtils,
    Localization: typeof Localization === "undefined" ? undefined : Localization,
    DecompressionStream: typeof DecompressionStream === "undefined" ? undefined : DecompressionStream
  };
}

function install(data, reason) {}

async function startup(data, reason) {
  spdfZoteroPlugin = SpdfZotero.createPlugin(spdfZoteroGlobals());
  await spdfZoteroPlugin.startup(data, reason);
}

function onMainWindowLoad(params) {
  if (spdfZoteroPlugin) spdfZoteroPlugin.onMainWindowLoad(params);
}

function onMainWindowUnload(params) {
  if (spdfZoteroPlugin) spdfZoteroPlugin.onMainWindowUnload(params);
}

function shutdown(data, reason) {
  if (spdfZoteroPlugin) spdfZoteroPlugin.shutdown(data, reason);
  spdfZoteroPlugin = undefined;
}

function uninstall(data, reason) {}
`;

const HEADER = `/*
 * SPDF for Zotero ${version}: https://spdf.joseluissaorin.com/integrations#zotero
 * MIT OR Apache-2.0 (LICENSE-MIT, LICENSE-APACHE). Generated by scripts/build.mjs from
 * integrations/zotero/src, with the engine-less core of spdf-format bundled in.
 */
`;

async function filesUnder(dir) {
  const out = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...(await filesUnder(p)));
    else out.push(p);
  }
  return out;
}

await rm(dist, { recursive: true, force: true });
await mkdir(out, { recursive: true });

const result = await build({
  entryPoints: [join(root, 'src/plugin.ts')],
  bundle: true,
  format: 'iife',
  globalName: 'SpdfZotero',
  platform: 'browser',
  target: ['firefox115'],
  charset: 'ascii',
  legalComments: 'none',
  minify: false,
  write: false,
  define: { __SPDF_ZOTERO_VERSION__: JSON.stringify(version) },
  // Globals the Zotero plugin sandbox lacks, provided as modules (see src/shims/).
  inject: [join(root, 'src/shims/structured-clone.ts')],
  logLevel: 'warning',
});
// esbuild escapes non-ASCII in strings but not in regular expressions or kept doc
// comments; \uXXXX means the same there (astral characters become surrogate pairs, which
// a /u regex reads as one code point), so escape whatever is left.
const toAscii = (text) => text.replace(/[\u0080-\uffff]/g, (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, '0')}`);
const bootstrap = toAscii(HEADER + result.outputFiles[0].text + HOOKS);
if (/[^\x00-\x7f]/.test(bootstrap)) throw new Error('bootstrap.js must be ASCII.');

const files = new Map();
files.set('bootstrap.js', Buffer.from(bootstrap, 'utf8'));
const manifest = JSON.parse(await readFile(join(root, 'addon/manifest.json'), 'utf8'));
manifest.version = version;
files.set('manifest.json', Buffer.from(JSON.stringify(manifest, null, 2) + '\n', 'utf8'));
for (const p of await filesUnder(join(root, 'addon/locale'))) {
  files.set(relative(join(root, 'addon'), p).split('\\').join('/'), await readFile(p));
}
for (const name of ['LICENSE-MIT', 'LICENSE-APACHE']) {
  try {
    files.set(name, await readFile(join(root, '../..', name)));
  } catch {
    /* licenses are optional in the package */
  }
}

for (const [name, data] of files) {
  const p = join(out, name);
  await mkdir(dirname(p), { recursive: true });
  await writeFile(p, data);
}
const xpi = join(dist, `spdf-zotero-${version}.xpi`);
await writeFile(xpi, zip([...files].map(([name, data]) => ({ name, data }))));
const size = (await readFile(xpi)).length;
console.log(`${relative(root, xpi)} (${size} bytes, ${files.size} files)`);
